### ISSUE TITLE
export for release crashs when file isn't found

### ISSUE THREAD

**Issue by hems** [polvo/polvo#22]
The compiler crashes and the name of the missing file isn't informed.

~ new_ui[master●] ⚡the -r
Merging files..

/Users/hems/git/my_awesomei/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:222
             "#{'not found for file'.yellow} " +

TypeError: Cannot read property 'bold' of undefined
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:222:35)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.reorder (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:205:12)
    at Optimizer.module.exports.Optimizer.merge_files (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:119:4)
    at Optimizer.module.exports.Optimizer.merge_everything (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:134:14)
    at Optimizer.module.exports.Optimizer.optimize (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/optimizer.coffee:38:13)
    at Tentacle.module.exports.Tentacle.optimize (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo/core/tentacle.coffee:105:7)
    at Polvo.module.exports.Polvo.compile (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo.coffee:93:8)
    at new Polvo (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/src/polvo.coffee:73:10)
    at Object.<anonymous> (/Users/hems/git/my_awesome/node_modules/theoricus/node_modules/polvo/bin/polvo:3:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by arboleya** [comment]
It seems the error is right inside the error notification, how paradoxical is that?

Apparently `id` of `file.id` is null.
https://github.com/serpentem/polvo/blob/master/src/polvo/core/optimizer.coffee#L223

Must to check it better.

**Comment by hems** [comment]
yeah weird things were happening due to some code i wrote that looked good, but actually didn't work.

i got surprised by the nonsense error message.

now everything is fine. the error was on my code, but i as i said, i didn't guess cause the error didn't pop on my object, it poped on polvo.
